### ISSUE TITLE
oic/cbor encoding to/from the wire, remove sol_vector

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#1080]
We changed the approach regarding memory allocation when we changed the internals to use cbor to use more memory allocation that we did before.

we should change it to iterator pattern that reads/writes directly to the "wire" (packet's payload).

hopefully before v1 so we can break api and do not keep the old behavior.

@lpereira can share some ideas.

**Comment by otaviobp** [comment]
Fixed when PR #1127 was merged.
