### ISSUE TITLE
implement LWM2M

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#1110]
LightWeight Machine-2-Machine is a widely used IoT protocol in the lines of CoAP and MQTT, we should support it. Actually it is used with CoAP

References:
 * https://en.wikipedia.org/wiki/OMA_LWM2M
 * https://github.com/eclipse/wakaama

**Comment by bdilly** [comment]
done by @cabelitos : https://github.com/solettaproject/soletta/pull/1464
