### ISSUE TITLE
platform: implement hostname set/get/monitor and node-types

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#1112]
We should implement a standard API to set, query and monitor hostname changes, also exposed as node-type.

In Linux, these would be implemented on top of http://www.freedesktop.org/wiki/Software/systemd/hostnamed/ (platform=systemd) or simply by executing the syscalls + /etc/hostname directly.

If any monitors, then it should monitor the service signals. Stop monitoring once all monitors are deleted.

The node type could be `platform/hostname` with `IN(string)` and `OUT(string)`. Connecting to `OUT` would add a monitor.

**Comment by cabelitos** [comment]
merged.
