### ISSUE TITLE
platform: implement date&time set/get/monitor

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#1113]
We should implement a standard API to set, query and monitor time and date changes, also exposed as node-type.

In Linux, these would be implemented on top of http://www.freedesktop.org/wiki/Software/systemd/timedated/ (platform=systemd) or simply by executing the syscalls + /etc/* directly.

If any monitors, then it should monitor the service signals. Stop monitoring once all monitors are deleted.

The node type could be `platform/time` with IN(timestamp) and OUT(timestamp). Connecting to OUT would add a monitor that notifies if system clock was changed (ie: user fixed it or timezone changed).

Similar nodes for `platform/timezone`.

Not sure we should expose RTC and NTP stuff.

**Comment by cabelitos** [comment]
merged.
