### ISSUE TITLE
platform: implement locale get/set/monitor and node-type

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#1114]
We should implement a standard API to set, query and monitor locale changes, also exposed as node-type.

In Linux, these would be implemented on top of http://www.freedesktop.org/wiki/Software/systemd/localedd/ (platform=systemd) or simply by executing the `setlocale()` + /etc/locale.conf directly.

If any monitors, then it should monitor the service signals. Stop monitoring once all monitors are deleted.

The node type could be `platform/locale` with `LANG(string)` and `LANG(string)` and also for other individual components of libC, such as `LC_NUMERIC`. Connecting to OUT would add a monitor.

Console/X11 keyboards shouldn't be covered.

**Comment by cabelitos** [comment]
merged.
