### ISSUE TITLE
Cover 100% C public API on documentation

### ISSUE THREAD

**Issue by glima** [solettaproject/soletta#1149]
Don't forget the samples -- we need much more text explaining what's going on each of them for newcomers.

**Comment by mbelluzzo** [comment]
I think its wise to split c-api docs (headers) from samples docs, specially because they are created in a different way and many of our samples may need re-work.

**Comment by glima** [comment]
That's OK. Would you edit this ticket and create the other for the samples, please?

Gustavo Lima Chaves
Software Engineer @ Intel
________________________________

**Comment by mbelluzzo** [comment]
Sure

**Comment by mbelluzzo** [comment]
Soletta Lib (considering my pr and bdilly's http):
**crypto** = 100%
**datatypes** = 100%
**io** = 100%

**comms** = 64%
**common** = 41%
**parsers** = 17% - WIP is a single file
**flow** = 16%

**Comment by bdilly** [comment]
@mbelluzzo concluded this task.

I've added checks on semaphoreci to avoid merges of new API without documentation.

This way we'll be sure to always have the whole API covered.
