### ISSUE TITLE
`make help` unavailable

### ISSUE THREAD

**Issue by siovene** [solettaproject/soletta#1155]
When encountering a problem in the configuration, `make` tells me:

    -e For more information/options, run: make help

however, `make help` fails with:

    make: *** No rule to make target `soletta_help', needed by `help'.  Stop.

**Comment by barbieri** [comment]
oops! Somehow it broke :-)

**Comment by bdilly** [comment]
Hi @siovene 

Thanks for spotting it.

It's fixed on master now.
