### ISSUE TITLE
sol-platform.h uses constant not defined in public headers: NSEC_PER_MSEC

### ISSUE THREAD

**Issue by gabrielschulhof** [solettaproject/soletta#1234]
sol-platform.h only includes sol-vector.h and no other file, and NSEC_PER_MSEC is not defined in either of those files.

I suppose sol-platform.h should include sol-util.h, which is where NSEC_PER_MSEC is defined, but sol-util.h does not appear to be a public header.

**Comment by ceolin** [comment]
Fixed on 7f4cdd6bb9a495944440d97725c4b2aac0cd525c
