### ISSUE TITLE
Export useful bit of `src/shared` and `sol-util.h`

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#1270]
These utilities are useful to us and likely useful to our users. Then we should export all that are not internal to soletta, things such as comparison (`sol_util_int_compare()`), timespec (`sol_util_timespec_get_current()`), macros as `sol_min()` and `sol_max()` and so on.

We must be sure all exported symbols and macros have `SOL_` or `sol_` prefix.

**Comment by ceolin** [comment]
https://github.com/solettaproject/soletta/pull/1298

**Comment by ceolin** [comment]
implemented on  https://github.com/solettaproject/soletta/pull/1304
