### ISSUE TITLE
OIC Client: sol_oic_client_resource_set_observable(_non_confirmable)? callback documentation mismatch

### ISSUE THREAD

**Issue by gabrielschulhof** [solettaproject/soletta#1319]
The documentation for ```sol_oic_client_resource_set_observable()``` says the callback has a boolean return value where ```true``` indicates the intention to keep observing and ```false``` indicates the intention to stop observing, but the declaration of the callback is ```void (*)(...)```.

**Comment by otaviobp** [comment]
Issue fixed in pr #1324. Can you check if it is ok for you?

**Comment by gabrielschulhof** [comment]
Looks good!

**Comment by otaviobp** [comment]
Pr merged
