### ISSUE TITLE
Double slash in some Make rules break compilation

### ISSUE THREAD

**Issue by thiagomacieira** [solettaproject/soletta#1328]
For example:

```
make: *** No rule to make target `src//modules/flow/oic/oic.json', needed by  `build/soletta_sysroot/usr/local/Soletta/include/soletta/sol-flow/oic.h'.  Stop.
```

Note the double slash in "src//modules". There is a rule to generate this file, but with a single slash.

I don't know which Makefile contains those rules. Grep can't find anything.

**Comment by bdilly** [comment]
@ceolin maybe @dorileo can help you with that.

**Comment by ceolin** [comment]
i can help with this. Thiago how can i reproduce it ? I've never faced this problem in my system.

**Comment by thiagomacieira** [comment]
I don't know what caused it. I got the latest version and typed gmake.

On OS X.

**Comment by ceolin** [comment]
ok, i'll check it correctly

**Comment by ceolin** [comment]
fixed https://github.com/solettaproject/soletta/commit/9f60a08b67bbbc85b2d49c93f5af68bded453fd7
