### ISSUE TITLE
Use of undeclared identifier 'ENOTUNIQ'

### ISSUE THREAD

**Issue by thiagomacieira** [solettaproject/soletta#1329]
```
./src//lib/flow/sol-flow-builder.c:484:21: error: use of undeclared identifier 'ENOTUNIQ'
            return -ENOTUNIQ;
                    ^
```

In files that aren't Linux-specific, please choose errno names *only* if they are defined in POSIX.

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html

**Comment by ceolin** [comment]
https://github.com/solettaproject/soletta/pull/1343 should solve this problem.

**Comment by thiagomacieira** [comment]
Or #1332.

**Comment by ceolin** [comment]
ohhh my bad, the fix was so simple that i've not even checked for prs.

**Comment by ceolin** [comment]
i'll merge you pr and close it.
