### ISSUE TITLE
I/O APIs: add UART write with tx buffer as byte array

### ISSUE THREAD

**Issue by zolkis** [solettaproject/soletta#1403]
Currently the signature for UART send is using ```unsigned char *tx``` for transmit buffer:
https://github.com/solettaproject/soletta/blob/master/src/lib/io/include/sol-uart.h#L150
```javascript
bool sol_uart_write(
    struct sol_uart *uart,
    const unsigned char *tx, unsigned int length,
    void (*tx_cb)(void *data, struct sol_uart *uart, unsigned char *tx, int status),
    const void *data);
```
Shouldn't the transmit buffer be a byte array ~~instead~~ in addition?
For instance other APIs like SPI use ```const uint8_t *tx``` which is would be more correct IMO also for UART, but you could also keep the string interface for convenience and backward comp.
https://github.com/solettaproject/soletta/blob/master/src/lib/io/include/sol-spi.h#L118

**Comment by zolkis** [comment]
If ```unsigned char *``` is actually defined as ```uint8_t *``` on all platforms then of course forget the above. Anyway using ```uint8_t *``` would make it more clear.

**Comment by barbieri** [comment]
I guess @ibriano forgot to change these, it should be `uint8_t *`

**Comment by ibriano** [comment]
Done
