### ISSUE TITLE
Platform: Locale category value may be enclosed in quotes [P2]

### ISSUE THREAD

**Issue by gabrielschulhof** [solettaproject/soletta#1460]
My ```/etc/locale.conf``` has

```
LANG="en_US.UTF-8"
```

and ```sol_platform_get_locale(SOL_PLATFORM_LOCALE_LANGUAGE)``` returns ```"\"en_US.UTF-8\""```.

It looks like quotes (both single and double) need to be stripped from the ```/etc/locale.conf``` value.

**Comment by cabelitos** [comment]
Check #1463

**Comment by cabelitos** [comment]
merged
