### ISSUE TITLE
Circular build warning during building from source

### ISSUE THREAD

**Issue by nirmalsinghania2008** [solettaproject/soletta#1598]
#### Circular build warning

During building soletta from source
after make command
make: Circular build/stage/modules/flow/converter/string-format.o <- build/stage/modules/flow/converter/string-format.o.dep dependency dropped.
is displayed
 
but the installation continues
is this a general warning?
#### Steps to reproduce

 1. cd soletta 
 2.make thirdparty-update
 3.make alldefconfig
4.make

Host OS and architecture: -Ububtu 14.04 x64

**Comment by glima** [comment]
There's a PR (https://github.com/solettaproject/soletta/pull/1940) fixing that.
