### ISSUE TITLE
Analog AIO interface not working

### ISSUE THREAD

**Issue by sragavan** [solettaproject/soletta#1601]
#### Task Description
Analog AIO api doesn't seem to be working. Tested with the below steps on flow as well.
#### Steps to reproduce

Open the device ip:8080 flow editor and open the Groove sample for Temperature sensor.
Run the source and it reports -273.150000C. Which is 0K and it should report real temperature.

#### Board information

Intel Edison/Soletta from github

**Comment by mbelluzzo** [comment]
If you are using Soletta Dev-app, the patch that fix this issue is'nt in yet (commit '38073d'). It should be in for beta 16. What you can do to fix this issue in the meanwhile is to compile Soletta master branch and overwrite the installation on your dev-app image.

**Comment by glima** [comment]
@mbelluzzo: is this fixed now?

**Comment by mbelluzzo** [comment]
yep
