### ISSUE TITLE
Doxygen standards: Add list of most frequently used commands

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1610]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Doxygen-standards
Instead of just linking to Doxygen's offical manual page about the commands list the commands that our team uses the most and a brief explanation for each of them. After the list we can still keep the link to the official page, "For a complete list of all commands available please refer to the official documentation at..." or something like that.

#### Dependencies
None

**Comment by bdilly** [comment]
done
