### ISSUE TITLE
Wiki Home: Add more highlight to stable downloads

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1620]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki
There should be more highlight to the stable downloads available to try Soletta out.

Review the text about DevApp to be friendlier and simpler.

#### Dependencies
None

**Comment by bdilly** [comment]
I reviewed the text of home and getting started and made some fixes.
I won't put too much light over pre built images since they're covering a small subset of boards.
