### ISSUE TITLE
uncrustify: Explain how to install it on other Linux distros

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1625]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/uncrustify
Right now there's only text for Arch Linux and Ubuntu and it'd be nice to add them for Fedora and Clear Linux too since they're also mentioned on other pages of our documents.

- [x]  Add instruction text for Fedora
- [ ] Add instruction text for Clear Linux

#### Dependencies
It'd be nice to have #1624 fixed so we don't have outdated information on any section.

**Comment by bdilly** [comment]
Done for Fedora.
For Clear it should be provided in the bundle related to soletta-dev or something like that.
