### ISSUE TITLE
Edison Instructions: Write all terminal snippets the same way

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1629]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Edison-Instructions
Some terminal snippets are shown as
```
[host]$ make install DESTDIR=<TMP_PATH>
```
While others are written as
```
sudo ifconfig usb0 192.168.2.2
```

When we need to perform as root always use <code>sudo</code> command on the terminal example unless we really need <code>su</code> 

- [ ] Write all terminal snippets as  <code>[host]$ </code>
- [ ] Write/use <code>sudo</code> commands on the snippets when root is needed, for instance on "Setup and Build a custom Edison Image" step 7 - Flash the board (AS ROOT)

#### Dependencies
None

**Comment by mbelluzzo** [comment]
Yocto section moved to EdisonYocto page and referenced on Meta-soletta one. This will problaby need a different work now, so I'm closing this one.
