### ISSUE TITLE
Galileo and Galileo Gen2 Instructions: Merge SDK tricks into main article

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1634]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Galileo-and-Galileo-Gen2-Instructions
Given that the SDK tricks listed on [Galileo's official SDK tricks](https://github.com/solettaproject/soletta/wiki/Galileo-and-Galileo-Gen2-Instructions#galileos-official-sdk-tricks) are always needed it's best to simply merge it into the main article in its appropriate place.

#### Dependencies
None

**Comment by mbelluzzo** [comment]
Isn't always needed. It's needed when you have to compile Soletta for Galileo(v1/v2) when using this sdk, thats why it's inside the article that explain how to do this. If we move to it's own article,  you would open a ticket asking us to explain why this is needed and when and to move this information closer to it's use.
