### ISSUE TITLE
Galileo and Galileo Gen2 Instructions: Better explain what PYTHONHOME modification is for

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1635]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Galileo-and-Galileo-Gen2-Instructions
Make it clear what the [Appendix - Modify 'PYTHONHOME'](https://github.com/solettaproject/soletta/wiki/Galileo-and-Galileo-Gen2-Instructions#modify-pythonhome) is for, what is the modification that must be performed and during which step this must be done.

#### Dependencies
None

**Comment by mbelluzzo** [comment]
Modify pythonhome is a section of #galileos-official-sdk-tricks that is reference and linked during the step on which this modification is needed. The explanation of why its needed is the opening text of this section.
