### ISSUE TITLE
Edison Instructions: Specify which Python packages are needed

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1639]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Edison-Instructions
On [Pre-requisites](https://github.com/solettaproject/soletta/wiki/Edison-Instructions#pre-requisites) replace the text "... and some additional Python packages)" with the full list of packages needed or a link to the official page that states which are the requirements.

#### Dependencies
None

**Comment by mbelluzzo** [comment]
Check updated version
