### ISSUE TITLE
How to report an issue: Improve information about paste tools

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1640]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/How-to-report-an-issue
On [Information needed for any kind of issue](https://github.com/solettaproject/soletta/wiki/How-to-report-an-issue#information-needed-for-any-kind-of-issue) explain what pastebin is and add a link to its homepage.
While we are at it also explain the option of using GitHub's gist.

- [x] Explain what pastebin is and add a link to its homepage
- [x] Explain GitHub's gist and a link to its official help page

#### Dependencies
None

**Comment by bdilly** [comment]
done
