### ISSUE TITLE
How to report an issue: Briefly explain the types of issue and info needed

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1643]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/How-to-report-an-issue
We have a couple of categories of issues but the person needs to browse the whole page before she knows it.
On [How to start](https://github.com/solettaproject/soletta/wiki/How-to-report-an-issue#how-to-start) briefly explain that there's common information needed for every issue and specific information for the different types of issues, listing them along with a short explanation about them. It'd be nice to also add a direct link to each one.

#### Dependencies
None

**Comment by bdilly** [comment]
done
