### ISSUE TITLE
Soletta Machine Learning: Light Sensor Tutorial: Solve redlink issue

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1648]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning:-Light-Sensor-Tutorial
On [Overview](https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning:-Light-Sensor-Tutorial#overview) there's a broken link on [How to add machine learning to flows](https://github.com/solettaproject/soletta/wiki/How-to-add-machine-learning-to-flows): fix it by adding the working link.

#### Dependencies
None

**Comment by bdilly** [comment]
looks like it was fixed already
