### ISSUE TITLE
Soletta Machine Learning: Light Sensor Tutorial: Improve page text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1655]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning:-Light-Sensor-Tutorial
On the [Overview](https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning:-Light-Sensor-Tutorial#overview) section it'd be nice to talk about the problem that is going to be solved -- this is currently done in the [Coding](https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning:-Light-Sensor-Tutorial#coding) section.

- [ ] Move the high level overview of the tutorial from Coding section to the Overview
- [ ] On Coding talk briefly about the steps that are going to be taking -- right now they are only listed as a bullet list

#### Dependencies
None

**Comment by nirmalsinghania2008** [comment]
Updated!

**Comment by bdilly** [comment]
thanks @nirmalsinghania2008

**Comment by gpaes** [comment]
@nirmalsinghania2008 pretty nice contribution!:)
