### ISSUE TITLE
Soletta Machine Learning: Light Sensor Tutorial: Specify what is *it*

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1656]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning:-Light-Sensor-Tutorial
On the [Modeling the solution](https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning:-Light-Sensor-Tutorial#modeling-the-solution) section, it is discussed "What is it trying to learn?" but nowhere on the text it's specified what is *it*. It might be obvious to some but not for all so we better make this explicit.
We can keep the bullet points but a small text discussing them would be greatly appreciated.

- [x] Specify what is "it"
- [ ] Add small text discussing what is going to be tackled to model the solution

#### Dependencies
None

**Comment by bdilly** [comment]
I've re-written some parts of these sections. I hope things are more clear now.
