### ISSUE TITLE
API Changes: Sol-Cerfiticate

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1658]
#### Task Description
Currently sol_certificate API only provides sol_certificate_ref() function. It would be nice to have an unref counter part.

- [ ] Create `sol_certificate_unref()` function and apply it to the code where necessary.

#### Dependencies
None.

**Comment by ceolin** [comment]
actually we have `sol_cert_unref()` but no `sol_cert_ref()` and the certificate is ref counted. I'm adding the `sol_cert_ref()`

**Comment by ceolin** [comment]
done
