### ISSUE TITLE
API Changes: Sol-Buffer

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1660]
#### Task Description

In order to keep our API consistent with soletta's style, some changes are required in Sol-Buffer.

- [ ] Fix typo in SOL_DECODE_UPERCASE  -  it should be UPPERCASE.
- [ ] In `sol_buffer_remove_data()` swap the arguments order  (`size` and `offset`)

#### Dependencies
None.

**Comment by kaspersky** [comment]
#1692
