### ISSUE TITLE
Add tests for sol_list

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1661]
#### Task Description

Currently sol_list does not have a test suit. One should be created.

- [ ] Write tests for sol_list - It should cover the whole API.
- [ ] Bonus task: Fix `SOL_LIST_INIT` Macro, since it causes segfault. Right know no one is using it, however we should provide a macro that works properly

#### Dependencies
None.

**Comment by amandawrcoelho** [comment]
@ceolin we can close this task
