### ISSUE TITLE
API Changes: Sol-str-slice

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1663]
#### Task Description

- [ ] Replace the `caseeq` keyword with`case_eq`. Example: `sol_str_slice_str_caseeq()` should be `sol_str_slice_str_case_eq()`
- [ ] `sol_str_slice_to_int()` should receive a pointer to `long int` instead of `int` as argument.

#### Dependencies
None

**Comment by ceolin** [comment]
Fixed !
