### ISSUE TITLE
API Changes: Sol-pin-mux

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1671]
#### Task Description

- [ ] In `sol_pin_mux_setup_gpio` `pin` should be an `int`.
- [ ] In `sol_pin_mux_setup_i2c` `bus` should be an `int`

#### Dependencies

** TODO: Link the i2c and gpio API changes here**

**Comment by bdilly** [comment]
after discussion with @ceolin and @ibriano we got to the conclusion these changes shouldn't be done since pin / bus can't be negative and would be inconsistent with others

so closing it
