### ISSUE TITLE
API Changes: boolean => bool

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1678]
#### Task Description

Usage of string `boolean` should be changed in our API (functions , structs) for `bool`

**Comment by nirmalsinghania2008** [comment]
u mean sol_flow_send_boolean_packet should be changed to sol_flow_send_bool_packet 
and other?

**Comment by bdilly** [comment]
@nirmalsinghania2008 yeah, exactly

**Comment by ceolin** [comment]
https://github.com/solettaproject/soletta/commit/7e216c36a6ef8f8d0aa297cccce68868e5d47950
