### ISSUE TITLE
Running SML in Galileo or Edison: Add introduction text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1683]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Running-SML-in-Galileo-or-Edison
Add an introductory text where we talk about why we have special steps for Galileo and Edison and briefly talk about the steps we are going to take to be able to run SML on those platforms.

#### Dependencies
None

**Comment by bdilly** [comment]
done
