### ISSUE TITLE
Soletta Machine Learning Quickstart: Add link to "Running SML in Galileo or Edison"

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1684]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning-Quickstart
Since there are special needs to setup SML for Galileo and Edison add a short text about this fact and a link to [Running SML in Galileo or Edison](https://github.com/solettaproject/soletta/wiki/Running-SML-in-Galileo-or-Edison).

#### Dependencies
None

**Comment by bdilly** [comment]
done
