### ISSUE TITLE
Soletta Machine Learning: Review fuzzy terms listing

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1686]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning
On the [Fuzzy terms](https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning#fuzzy-terms) section we have a plain listing of the terms, which is not useful.
Add short paragraphs on each one explaining them.

#### Dependencies
None

**Comment by nirmalsinghania2008** [comment]
This is completed!!

**Comment by gpaes** [comment]
@nirmalsinghania2008 Great, thanks!
