### ISSUE TITLE
Soletta Machine Learning: Add code samples to document

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1687]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Soletta-Machine-Learning
Add code snippets throughout the document to better illustrate what is being discussed.

#### Dependencies
None

**Comment by bdilly** [comment]
Instead of adding code snippets we preferred to link the source code, so we're sure it won't be outdated and stop building or working.

All samples are linked to source code (and eventually tutorials)
