### ISSUE TITLE
Samples:Calamari Lure: Improve page text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1698]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Samples:Calamari-Lure
The leading text "src/samples/flow/minnow-calamari" is shown without context and the samples have no explanations of what they are about -- they only have their expected outputs.

- [ ] Add context for "src/samples/flow/minnow-calamari", explaining that this is a directory that holds the given samples
- [ ] Explain briefly what each sample is about and its purpose

#### Dependencies
None

**Comment by bdilly** [comment]
done
