### ISSUE TITLE
Samples:Calamari Lure: Rename calamari-7seg-segments sample

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1700]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Samples:Calamari-Lure
The [calamari-7seg-segments](https://github.com/solettaproject/soletta/wiki/Samples:Calamari-Lure#calamari-7seg-segmentsfbp) currently does not have a very meaningful name. Renaming it to something closer to what it performs would help the people browsing the samples.

- [ ] Rename the sample to 'calamari-7seg-play', 'calamari-7seg-display' or something along these lines
- [ ] Ensure that all old links now point to the renamed sample, leaving no broken links

#### Dependencies
None

**Comment by bdilly** [comment]
The point is to contrast it with 7seg-value.

There are basically two ways to set your 7seg display:
 * setting up each segment
 * setting a single value (it handles what segments must be on or off).

I've added a explanation about it on 7seg samples description, but didn't change the name
