### ISSUE TITLE
Strings on Soletta flows: Sum the node list up

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1704]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Strings-on-Soletta-flows
At the top section there's a big list of string nodes: replace it with most used ones and add a link to the Cheat Sheet for its full list.

#### Dependencies
None

**Comment by bdilly** [comment]
@gpaes , while reading this page I saw that actually it had faulty links, but the explicit list of nodes has an important role on this page, if you click on each node type it jump to further explanation / usage example. So I believe we can keep them with fixed links.

Ptal and see if you agree it's good enough.

**Comment by gpaes** [comment]
@bdilly Thanks for fixing the links! Let's leave them as is then. If needed we can revisit this.
