### ISSUE TITLE
API Changes: Flow-Metatypes

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1713]
#### Task Description
- [ ] Remove typdefs
- [x] Replace all occurences of metatype to meta_type. Example: `sol_flow_metatype_context` to `sol_flow_meta_type_context`
- [ ] Function `read_file` in `sol_flow_metatype_context` should receive a `struct sol_buffer` as argument instead of `const char **buf, size_t *size`

#### Dependencies

None.

**Comment by barbieri** [comment]
I'm not sure i like meta_type more than metatype... :-D

**Comment by cabelitos** [comment]
Me too :[

**Comment by bdilly** [comment]
ok, so let it as metatype

**Comment by ceolin** [comment]
well, use typedef there will turn the illegible, i.e
`int (*(sol_flow_metatype_get_generate_code_start_func)(const struct sol_str_slice name))(const struct sol_flow_metatype_context *ctx, struct sol_buffer *out);`

i think is better let as it is.

**Comment by ceolin** [comment]
done
