### ISSUE TITLE
Packages: Rename ArchLinux package soletta-git to soletta-nightly

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1725]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Packages
ArchLinux currently has two packages, soletta for releases and soletta-git for bleeding edge versions but both are git packages so the second one is not very meaningful. Renaming it to soletta-daily, soletta-nightly or something like that would help.

#### Dependencies
None

**Comment by bdilly** [comment]
I'm wondering if -git isn't a standard way to name such kind of packages on Arch.

So let's see what @anselmolsm say about it.

**Comment by anselmolsm** [comment]
-git is a standard for this kind o packages on Arch Linux

**Comment by gpaes** [comment]
Thanks @bdilly and @anselmolsm, I'm going to close the ticket then!
