### ISSUE TITLE
Packages: Review Soletta casing throughout the text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1726]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Packages
Sometimes Soletta is spelled as Soletta and sometimes as soletta. If we're talking about the package, write it as **soletta** as it's done for **libsoletta-dev** and use Soletta casing for the other cases.

#### Dependencies
None

**Comment by bdilly** [comment]
done
