### ISSUE TITLE
API Changes: IIO

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1742]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

 - [ ] Rename `sol_iio_device_trigger_now()` to `sol_iio_device_trigger()`
 - [ ] Change return type of functions that may fail to return error code instead of boolean `false`. Example: `sol_iio_read_channel_value()`

**Comment by amandawrcoelho** [comment]
We can close this :D

**Comment by ceolin** [comment]
certainly !!! Thanks
