### ISSUE TITLE
Porting: Integrate "FBP applications" section into "Flow"

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1746]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Porting#fbp-applications
Is the [FBP applications](https://github.com/solettaproject/soletta/wiki/Porting#fbp-applications) section a subtopic of [Flow](https://github.com/solettaproject/soletta/wiki/Porting#flow)? If so, we should update the document to represent that correctly with the proper topic hierarchy.

#### Dependencies
None

**Comment by bdilly** [comment]
done
