### ISSUE TITLE
API Changes: Opaque structs

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1750]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

Review opaque structs in Soletta's API and add any missing "@struct" doxygen command with struct documentation.

**Comment by cabelitos** [comment]
https://github.com/solettaproject/soletta/pull/2182

**Comment by cabelitos** [comment]
merged
