### ISSUE TITLE
Logic constructs on Soletta flows: Add syntax highlight for C snippets

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1751]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Logic-constructs-on-Soletta-flows
There are a couple of C snippets without proper syntax highlighting -- adding the correct programming language name on each snippet will solve that.

#### Dependencies
None

**Comment by bdilly** [comment]
Problem is github doesn't has support for FBP syntax.
But if tested it with prolog and result is good =)

**Comment by edersondisouza** [comment]
On 29-03-2016 18:01, Bruno Dilly wrote:
> Problem is github doesn't has support for FBP syntax.
> But if tested it with prolog and result is good =)

Prolog? I was using sh... is it better?

**Comment by gpaes** [comment]
@bdilly Prolog indeed yields good results! If there are no great harms I guess we should include this information bit to our **Contributing to the wiki** page.:)
