### ISSUE TITLE
API Changes: EFIVARS

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1759]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

 - [ ] Macros and inline functions missing docs. Review CREATE_BLOB and CREATE_BUFFER
 - [ ] `read_raw()` requires better documentation

**Comment by ceolin** [comment]
https://github.com/solettaproject/soletta/pull/2150/commits/ebe1f8f3d3b7b69749846595542aeb540683e4e2
