### ISSUE TITLE
Logic constructs on Soletta flows: Add graphical depiction of flow samples

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1760]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Logic-constructs-on-Soletta-flows
There are a couple of flow samples that do not have their graphical version depicted -- solve that by adding them.

#### Dependencies
None

**Comment by bdilly** [comment]
done, I've added diagrams for all fbp snippets.
