### ISSUE TITLE
Quickstart: Review terminal examples

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1771]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Quickstart
Review the terminal and sh examples to add syntax highlight and command prompt.

- [x] Add syntax highlight to sh examples
- [x] Add command prompt to terminal examples

#### Dependencies
None

**Comment by bdilly** [comment]
Hey @gpaes , I wasn't able to find the sh examples you're mentioning.
Could you please be point me to it?

**Comment by gpaes** [comment]
@bdilly for instance on the block:
$ export LD_LIBRARY_PATH=/path/to/lib/:$LD_LIBRARY_PATH
$ export PKG_CONFIG_PATH=/path/to/lib/pkgconfig:$PKG_CONFIG_PATH

Or do you think it's not useful to have them syntax-highlighted?

**Comment by bdilly** [comment]
syntax-highlight is good, for sure

For sh on github it's not as interesting as it could be though (almost no changes at all)

Anyway, change done
