### ISSUE TITLE
readme.md: Add direct download links to releases

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1779]
#### Task Description
To make it easier to people to try Soletta out we must update readme.md with direct download to its stable releases for the supported boards. This section should be highlighted, being placed as high as possible on the document.

#### Dependencies
None

**Comment by bdilly** [comment]
@gpaes  , not sure about this one.

Releases for supported boards may be done in different ways, we could have images generated with Ostro, Clear, regular Linux distros as Fedora or Arch.

So keeping all this data updated on README doesn't seem the best approach to me.

Couldn't we just keep it in our Home wiki page or something like that?

**Comment by bdilly** [comment]
actually I believe my idea is something like what was proposed here: #1785

**Comment by gpaes** [comment]
@bdilly That sounds pretty nice!

**Comment by bdilly** [comment]
cool, so I'm closing this one

thanks
