### ISSUE TITLE
soletta-small-oses-samples: Improve readme

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1784]
#### Task Description
Page: https://github.com/solettaproject/soletta-small-oses-samples
Improve readme by turning it into a md file with its formatting and move the task list at the bottom to the issues list.

- [x] Move from plain readme file to readme.md
- [x] Move task list from readme to the Issues page

#### Dependencies
None

**Comment by bdilly** [comment]
I've created issues on it's repository tracker (not soletta's)

Also PR https://github.com/solettaproject/soletta-small-oses-samples/pull/12 should take care of the other point.

Thanks
