### ISSUE TITLE
Quickstart: Add section to direct downloads of pre-build images

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1785]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Quickstart
Add a section with the links to the supported pre-build images:
* https://github.com/solettaproject/soletta/wiki/Installing-Intel%C2%AE-Edison-pre-built-image
* https://github.com/solettaproject/soletta/wiki/Installing-Intel%C2%AE-Galileo-Gen2-pre-built-image
* https://github.com/solettaproject/soletta/wiki/Installing-Minnowboard-max-pre-built-image

#### Dependencies
None

**Comment by bdilly** [comment]
done
