### ISSUE TITLE
Remove core.light and use oic.r.light.brigthness in soletta oic samples

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1789]
#### Task Description

Now that we have OIC data models no need to provide custom resource types for it.

**Comment by bdilly** [comment]
hmmm... actually it seems like they don't provide something like our light model.
They only provide the brightness. Most probably if it's off it should provide brightness == 0 and that's all.

In this case I'm inclined to let our custom data model (maybe even as an example of how to create custom stuff). What do you guys think about it?

@otaviobp @ceolin ^

**Comment by otaviobp** [comment]
I think that we don't have a good light model in the IoT Data Models repository. We have 2 resources for similar cases (oic.r.light.dimming and oic.r.light.brightness), but we don't have a light.switch.
One guy used the oic.r.switch.binary resource as a resource to turn the lights on/off in one example in IoTivitity dev day. It would be nice to have one resource that is a light that includes oic.r.light.brightness and oic.r.switch.binary.
As the main IoTivity samples are using a resource that is like the core.light we have in Soletta, I would keep it and close this task. Let's keep following updates in the repository to see if they add something new to it.

**Comment by bdilly** [comment]
@otaviobp yeah, it sounds like a plan

Let's see if they provide something similar soon. Closing it.
