### ISSUE TITLE
Installing Intel® Galileo Gen2 pre built image: Improve page text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1809]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Installing-Intel%C2%AE-Galileo-Gen2-pre-built-image
Rework the text to match the current formatting used on https://github.com/solettaproject/soletta/wiki/Installing-Intel%C2%AE-Edison-pre-built-image

#### Dependencies
None

**Comment by bdilly** [comment]
done
also a few improvements done on edison's page
