### ISSUE TITLE
Installing Minnowboard max pre built image: Improve page text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1810]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Installing-Minnowboard-max-pre-built-image
Rework the text to match the current formatting used on https://github.com/solettaproject/soletta/wiki/Installing-Intel%C2%AE-Edison-pre-built-image

#### Dependencies
None

**Comment by bdilly** [comment]
done
