### ISSUE TITLE
API Changes: Review I/O API looking for convergence

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1819]
#### Task Description

It would be nice to review all I/O API and try to make they all look the same.

They should be async, callbacks should pass data pointer as first parameter, etc

But also they should look similar. E.g:
 * if in a protocol you add elements one by one using _add(*element) and other add an array of elements you should go with the same for both - if possible
 * if you initialized some modules instances passing a config and in others set config with a specific call

Go through all headers on `src/lib/io/include/` and be happy

**Comment by cabelitos** [comment]
fixed
