### ISSUE TITLE
MinnowBoard MAX Instructions: Add direct download link

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1833]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/MinnowBoard-MAX-Instructions
Now we have downloadable releases for the Galileo boards so we should add direct downloads to the top of the page

#### Dependencies
None

**Comment by bdilly** [comment]
done

**Comment by gpaes** [comment]
@bdilly Just a quick note, that address is not valid anymore, the content lives in https://github.com/solettaproject/soletta/wiki/Building-Soletta-for-MinnowBoard-MAX. It'd be nice to guarantee that there are no broken links pointing to the old page.
I will try to check this next week but help is always appreciated.
