### ISSUE TITLE
Failed to run example in the spec for GPIO on Ostro image#435

### ISSUE THREAD

**Issue by wanghongjuan** [solettaproject/soletta#1949]
#### Steps to reproduce

 1. Copy the example code to a file, named as gpio-example.js, then copy it to test device.
 2. Update the code and run the example file:
```
var gpio = require("gpio");
```
change the require content "gpio" to the path of lib gpio.js and update
```
console.log("GPIO pin " + pin.pin " value changed to " + event.value);
```
to 
```
console.log("GPIO pin " + pin.pin " + value changed to " + event.value);
```
Then run:
```
node gpio.js
```

#### Board information

Target OS and platform: Ostro image#435(https://download.ostroproject.org/builds/ostro-os/2016-04-26_13-41-09-build-435/) and Edison

#### Logs

 * Soletta version (top commit hash): tag(v1_beta19), commit id(6a7bc32)
Only show below message:
```
GPIO pin undefined open for writing
```
I think it should show all console log messages.
The other specifications(e.g. I2C, PWM, SPI,UART) have the similar situation as GPIO, the example in the specification can not access the test fluky.

**Comment by baleboy** [comment]
According to @nagineni you should require the API with `require("soletta/gpio")`

**Comment by wanghongjuan** [comment]
Unfortunately, I get the same issue. Is there need other precondition? for example, need to connect other sensors?

**Comment by nagineni** [comment]
The example in the spec is incorrect, so please use the samples in this commit https://github.com/solettaproject/soletta/pull/1950/commits/06305496

**Comment by wanghongjuan** [comment]
OK,  what about other specifications(e.g. I2C, PWM, SPI,UART)? they have the similar situation as GPIO, the example in the specification can not access the test fluky.

**Comment by nagineni** [comment]
Look at samples in https://github.com/solettaproject/soletta/pull/1951/commits/73b31c2d2f for PWM and AIO. You should be able to run examples in the spec with little modifications for the other APIs. I will add more samples later.

**Comment by wanghongjuan** [comment]
Thanks, I will try to run them.

**Comment by zqzhang** [comment]
> The example in the spec is incorrect

@zolkis are you going to update the examples in the specs? Thanks.
