### ISSUE TITLE
Broken link in OIC JS API spec

### ISSUE THREAD

**Issue by gabrielschulhof** [solettaproject/soletta#2130]
In https://github.com/otcshare/iotivity-node/issues/54 @wanghongjuan wrote:
> As the spec that the link in the content of `Abstract` should be available . 
> `This document presents a JavaScript API for OIC Core Specification, based on the Soletta C API.`
> The link for `OIC` and `Soletta C API` can be open, but get `Page Not Found` when open the `Core Specification`.

@zolkis please fix the broken link to the Core Specification in the spec!

**Comment by bdilly** [comment]
@gabrielschulhof it's now fixed on Soletta, but it won't be reflected on  https://github.com/otcshare/iotivity-node/blob/master/README.md since your pointing to the Soletta file on tag v1_beta19 instead of master branch.

Anyway, it's fixed on Soletta.

Thanks
