### ISSUE TITLE
IIO: add sample for iio/proximity-sensor

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#2207]
The recently added node type iio/proximity-sensor is missing any sample.
It would be great to have one just like all the others under the same category.

**Comment by bdilly** [comment]
Hi @yongli3 ,

please, would you be able to help us on that?

I lack hardware to do it myself. Also I suppose you have written one when you tested it before merging the code.

**Comment by yongli3** [comment]
@bdilly No problem !

**Comment by bdilly** [comment]
Thanks a lot, @yongli3 
PR merged, ticket closed =)
