### ISSUE TITLE
Package: Update Fedora package

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#2237]
#### Task Description
The latest Fedora package on the https://github.com/solettaproject/soletta/wiki/Packages page is from is 04 Dec 2015.

#### Dependencies
None

<i>Edit: fixed minor typo</i>

**Comment by bdilly** [comment]
@gpaes it'll be updated with V1 release.
So stay tuned =)

**Comment by gpaes** [comment]
@bdilly Cool!!:D

**Comment by ceolin** [comment]
@glima could you update this info ?

**Comment by glima** [comment]
Done.
