### ISSUE TITLE
doc: strange line in documentation

### ISSUE THREAD

**Issue by cmarcelo** [solettaproject/soletta#2248]
In documentation page

http://solettaproject.github.io/docs/c-api/group__HTTP__CLIENT.html

The line that describes sol_http_client_connection_cancel() and sol_http_client_request_with_interface() functions have extra "struct sol_http_client_connection" as return values.

**Comment by cmarcelo** [comment]
![strange-doc](https://cloud.githubusercontent.com/assets/10478/16923240/9f4f5434-4cef-11e6-9096-18a6b1d97d00.png)

**Comment by bdilly** [comment]
I believe it's somehow related to SOL_ATTR_WARN_UNUSED_RESULT SOL_ATTR_NON_NULL(2, 4);

**Comment by bdilly** [comment]
yeah, looks like doxygen isn't able to deal very well with __attribute__

I'll send a PR for this issue soon

**Comment by bdilly** [comment]
ouch, I pushed the commit fixing it directly to master when I merged the fix for #2247 
Anyway, it seems to be fixed now.
If not, please let me know.
Thanks

**Comment by cmarcelo** [comment]
Instead, would be possible to set the macro SOL_ATTR_WARN_UNUSED_RESULT to empty when DOXYGEN_RUN is set? That way we only change where the SOL_ATTR... is defined, not in all places that use it.

**Comment by bdilly** [comment]
uhm... most probably it would be possible to do something like that, indeed.
Setting all these macros making doxygen fail to empty should work as well

**Comment by cmarcelo** [comment]
If it works, it's better. Otherwise to use those Soletta macros, one always will have to put two more lines for Doxygen ifdefs.
