### ISSUE TITLE
Disabling Worker thread breaks the build

### ISSUE THREAD

**Issue by rchiossi** [solettaproject/soletta#473]
From a clean master branch:

make alldefconfig
mane menuconfig
Uncheck "Core Library -> Worker Thread Support" and save
make

What you get:
./build/soletta_sysroot/usr/lib//libsoletta.so: undefined reference to `sol_worker_thread_cancel'
./build/soletta_sysroot/usr/lib//libsoletta.so: undefined reference to `sol_worker_thread_new'

**Comment by cmarcelo** [comment]
#505 should fix this. Checked locally and works now.
