### ISSUE TITLE
Ubuntu Package

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#513]
We should provide Ubuntu package and a PPA.

**Comment by anselmolsm** [comment]
Status update: debian/* done, it builds and works locally. Howver, I need to check what's wrong according to launchpad's buildbot.

**Comment by anselmolsm** [comment]
The package generation worked last Friday.
I'll make it follow the Debian/Ubuntu naming rules (libsoletta instead of soletta).

**Comment by anselmolsm** [comment]
libsoletta, libsoletta-bin and libsoletta-dev: https://launchpad.net/~anselmolsm/+archive/ubuntu/solettaproject/+packages
I'll create a dedicated ppa for Soletta later.
