### ISSUE TITLE
ArchLinux Package

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#514]
We should provide ArchLinux package and repository.

**Comment by anselmolsm** [comment]
https://aur.archlinux.org/packages/soletta-git , currently using alldefconfig. This could be improved.

I'm thinking about a separate package for offiline docs (to not inflate soletta-git's makedepends due to graphviz, doxygen, etc).

**Comment by barbieri** [comment]
great! add that to wiki and/or README.md and close this issue
