### ISSUE TITLE
some tests contained in src/test-fbp failed to run in Minnowboard

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#546]
fbp tests contained in soletta/src/test-fbp failed to run and returned the following type of output:

'Couldn't resolve type name'

The complete list of error messages is listed in the link below: 

http://pastebin.intel.com/view/6b4c1888

Thank you.

**Comment by anselmolsm** [comment]
Please, provide the sha1.
Reopen with the proper info.
