### ISSUE TITLE
[P2] Tests in /src/test-fbp and src/samples/flow/unix-socket failed in Galileo Gen2

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#548]
SHA1: ece20c7fde9c310f83b14048701b2c57619f2800

Error messages like the following:

'Couldn't resolve type 'test/result' of node 'test_compare_red_byte' '

are returned on the execution of the fbp tests located in soletta/src/test-fbp.

The complete list of error messages is listed in the link below: 

http://pastebin.intel.com/view/46e6ddf4 are executed in a Galileoboard Gen2.

Thank you.

**Comment by mbelluzzo** [comment]
Probably the same mistake described on #551 in happening here in regard of samples/unix-socket. 
@dborquez could you retry this one as well?

**Comment by dborquez** [comment]
@mbelluzo you are correct, this is not a bug.
