### ISSUE TITLE
[P3] Tests in src/test-fbp failed to run in minnowboard

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#549]
sha1:c63851b3d79dd89cf421874fc826494b1e886618

fbp tests contained in soletta/src/test-fbp failed to run and returned the following type of output:

'Couldn't resolve type name'

The complete list of error messages is listed in the link below: 

http://pastebin.intel.com/view/6b4c1888

Thank you.

**Comment by brunobottazzini** [comment]
Retested and the expected issue was not found. Everything worked normally.
