### ISSUE TITLE
we should separate CFLAGS, HOSTCFLAGS and TARGETCFLAGS

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#576]
While building, if we provide a custom CFLAGS such as `-march=i586` it will be used for both cross compiling and compilation of kbuild, that will make configure targets to fail.

Of course the same applies to LDFLAGS.

**Comment by dorileo** [comment]
I checked that case and I understand this case doesn't apply. The kconfig uses the ```HOST_CFLAGS``` and ```HOSTEXTRA_CFLAGS``` var and the ```CFLAGS``` value is never appended to it, do you have an easy way to reproduce what you've noticed?

**Comment by barbieri** [comment]
confirmed. It was a mess up in my setup.
