### ISSUE TITLE
[P2] string related tests contained in soletta/src/test-fbp/ failed to run in Galileo board G2.

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#663]
soletta v1_beta2 sha1: 3baae03daa72e6c0587a17c7750a463c813b4e55

The following tests failed to run:

string-compare.fbp
string-lower-upper.fbp
string-concat.fbp
string-regexp-search.fbp
string-length.fbp

A complete list of returned errors is founded in the following link:

http://pastebin.com/hCVRyJZY

Thank you.

**Comment by mbelluzzo** [comment]
string tests right now were maybe to stress the use of ICU. When compiling to galileo and edison, a priori you don't have ICU, so the default backend is used and thus those tests don't work. We will release a set of tests to exercise both backends soon.

**Comment by mbelluzzo** [comment]
@dborquez can you confirm that this is solved? We now have ascii tests but the icu tests are still supposed to fail if you dont have icu.

**Comment by dborquez** [comment]
I have tested the V1 Beta 6 (a1adfd1699fffae01e6ec0beda44bc7865923766) and it works.
