### ISSUE TITLE
linux-micro kmod module

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#676]
Implement a kmod service for linux-micro, it should follow systemd's modules-load.d(5) specification and use libkmod to do the actual work. The existing module `sysctl` loads in a similar fashion and should be used as base. Locations:

```
       /etc/modules-load.d/*.conf
       /run/modules-load.d/*.conf
       /usr/lib/modules-load.d/*.conf
```

It would be nice to listen for netlink messages saying new devices were added and use libkmod to check aliases (ie: load module for `pci:v00008086d00000958sv*sd*bc*sc*i*` will load `iosf_mbi`)

**Comment by dorileo** [comment]
implemented on 5d986ddfd5abb1e93479a2ff58c11c91faf3200e
