### ISSUE TITLE
linux-micro debug support (gdbserver)

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#677]
linux-micro will need a special trick to be debugged: we need to check debug is needed (ie: kernel command line `sol-debug=1`) and in that case we check we're PID1, if so we need to `fork()` and keep a minimal and safe PID1, doing all the work from the child. We should also check if `gdbserver` exists and attach it to the child (or spawn the child using `gdbserver`).

**Comment by dorileo** [comment]
implemented on 358df2f03d929c75c076142b1e8a547eff55f1fa
