### ISSUE TITLE
[P2] old glibc produces the error msg: /src/shared/sol-util.c:49:1: error: unknown type name 'locale_t' at compilation time

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#722]
Compiler error impedes build soletta for Galileo board.

Steps to reproduce the issue:

- The procedure followed is the described in the wiki to compile soletta for Galileo plattform:https://github.com/solettaproject/soletta/wiki/Galileo-and-Galileo-Gen2-Instructions).

Below is error returned by make:
./src/shared/sol-util.c:49:1: error: unknown type name 'locale_t
./src/shared/sol-util.c:63:26: error: 'LC_ALL_MASK' undeclared (first use in this function)

The complete output is in the next link: http://pastebin.com/ZrueV2Nm

Thank you.

**Comment by anselmolsm** [comment]
Fixed in tag 1beta_6.
