### ISSUE TITLE
review node type options to use basic types

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#724]
Currently we map "int" to "irange", "float" to "drange" and sometimes these are too-much. Take GPIO pins, for instance, we're interested in a single integer to represent that as the other 3 (min, max, step) are meaningless in such context.

Then we should introduce new mappings for "irange_spec"/"irange" and "drange_spec"/"drange" and use them where a range specification is needed (but not the value) or the whole set of members are needed (ie: constants).

**Comment by bdilly** [comment]
all changes merged. we're done.
