### ISSUE TITLE
automatically load conffiles

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#725]
We should have a standard lookup paths to load configuration files from, such as the name of the current application (binary or the FBP name if using `sol-fbp-runner` or `sol-fbp-generator`), as well as use the board name as in `sol_platform_get_board_name()`.

An idea is the following (from highest to lowest priority):
 * envvar `$SOL_FLOW_MODULE_RESOLVER_CONFFILE`
 * `./sol-flow-$APPNAME-$BOARD_NAME.json`
 * `$PKGSYSCONFDIR/sol-flow-$APPNAME-$BOARD_NAME.json`
 * `./sol-flow-$APPNAME.json`
 * `$PKGSYSCONFDIR/sol-flow-$APPNAME.json`
 * `./sol-flow.json`
 * `$PKGSYSCONFDIR/sol-flow.json`

Please add proper `SOL_DBG()` before trying to load each component so it's easy to debug which file is being used and those that failed (didn't exist or failed to load).

**Comment by dorileo** [comment]
implemented on 6ffdd6bcbcdf97bf70ca111706de5b45bef5b75e
