### ISSUE TITLE
linux-micro automount module

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#742]
In larger systems we have a set of tools to handle automount, such as udev and blkid to detect and flag devices that are later handled by udisks, that will mount them.

Linux-micro should provide module that is not as capable, but will at least mount media from mmc/usb. Since linux-micro is basically a single-user system, all we need to do is the shared mode that mounts /run/media/MOUNTPOINT. If we're linked with libblkid we can get more information about the device and keep a stable mount point. Otherwise we should use heuristics such as try to mount ext4/ext3/vfat and use the device name as mount point.

Devices can be discovered using netlink messages that expose new devices, likely to be shared with #676. Eventually we should do this as a generic `sol_udev` API that uses `libudev` when platform is `systemd` and direct handling in the other cases -- or always force libudev, need to check if it requires `udevd` (daemon) and the amount of code it brings in to `libsoletta.so`. 

If possible try to mount using the `mount(2)` syscall, if it does not work then fallback to `mount(1)` binary.

(This is **not a blocker** for v1)

**Comment by dorileo** [comment]
implemented on b039721b81ba46dbea889b603cdc054cc3ac4ef8
