### ISSUE TITLE
JSON Packets & Node Types

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#746]
It would be nice to have a JSON packet type, it's basically the same as the string, but will be used to differentiate ports and avoid feeding random text to JSON processing nodes. Of course one can add converters from `BLOB` and `STRING`, that will take care of validating using `sol-json.h` and if it passes will forward the packet.

Suggested Packet Types:
 * `JSON_OBJECT`: used for objects (`{...}`)
 * `JSON_ARRAY`:  used for arrays (`[...]`)

These packets should be implemented on top of `struct sol_blob` and keep references to the underlying memory, do not duplicate it to get slices. All other JSON types should be implemented on top of basic types such as `IRANGE`, `DRANGE`, `STRING`, `BOOLEAN`.

## Reading JSON

In order to make FBP easier to deal with JSON, we should offer nodes based on JSONPath http://goessner.net/articles/JsonPath/ to extract properties. This allows to reach a string or integer nested into deep structure with a single node.

Suggested Node Types:
 * `json/object-get-path`:
    * Options:
      * `path` (string): the JSON path to access the child element.
    * Input Ports:
      * `IN` (json object, required): the input json to get the child element
      * `PATH` (string, optional): allows changing the `path` given as option.
    * Output Ports:
      * `STRING` (string): the string at the given path.
      * `BOOLEAN` (boolean): the boolean at the given path.
      * `INT` (irange): the integer number at the given path (min=INT32_MIN, max=INT32_MAX, step=1)
      * `FLOAT` (drange): the floating point number at the given path (min=-DBL_MAX, max=DBL_MAX, step=DBL_MIN)
      * `OBJECT` (json object): the child JSON object at the given path.
      * `ARRAY` (json array): the child JSON array at the given path.
      * `NULL` (empty): empty packet if the object is `null``
 * `json/object-get-key`:
    * Options:
      * `key` (string): the key of the object child to access.
    * Input Ports:
      * `IN` (json object, required): the input json to get the child element
      * `KEY` (string, optional): allows changing the `key` given as option.
    * Output Ports:
      * `STRING` (string): the string at the given key.
      * `BOOLEAN` (boolean): the boolean at the given key.
      * `INT` (irange): the integer number at the given key (min=INT32_MIN, max=INT32_MAX, step=1)
      * `FLOAT` (drange): the floating point number at the given key (min=-DBL_MAX, max=DBL_MAX, step=DBL_MIN)
      * `OBJECT` (json object): the child JSON object at the given key.
      * `ARRAY` (json array): the child JSON array at the given key.
      * `NULL` (empty): empty packet if the object is `null``
 * `json/object-length`: (is this useful other than debug?)
    * Input Ports:
      * `IN` (json object, required): the input json to count elements
    * Output Ports:
      * `OUT` (irange): the number of child elements
 * `json/object-all-keys`:
    * Input Ports:
      * `IN` (json object, required): the input json to get all keys
    * Output Ports:
      * `OUT` (string): a single key in this object. Multiple packets may be emitted for every input packet.
      * `EMPTY` (boolean): if object is empty, then `true`, otherwise `false`.
 * `json/array-get-path`:
    * Options:
      * `path` (string): the JSON path to access the child element.
    * Input Ports:
      * `IN` (json array, required): the input json to get the child element
      * `PATH` (string, optional): allows changing the `path` given as option.
    * Output Ports:
      * `STRING` (string): the string at the given path.
      * `BOOLEAN` (boolean): the boolean at the given path.
      * `INT` (irange): the integer number at the given path (min=INT32_MIN, max=INT32_MAX, step=1)
      * `FLOAT` (drange): the floating point number at the given path (min=-DBL_MAX, max=DBL_MAX, step=DBL_MIN)
      * `OBJECT` (json object): the child JSON object at the given path.
      * `ARRAY` (json array): the child JSON array at the given path.
      * `NULL` (empty): empty packet if the object is `null``
 * `json/array-get-at-index`:
    * Options:
      * `index` (int): the index of the child element to access.
    * Input Ports:
      * `IN` (json array, required): the input json to get the child element
      * `INDEX` (int, optional): allows changing the `index` given as option.
    * Output Ports:
      * `STRING` (string): the string at the given index.
      * `BOOLEAN` (boolean): the boolean at the given index.
      * `INT` (irange): the integer number at the given index (min=INT32_MIN, max=INT32_MAX, step=1)
      * `FLOAT` (drange): the floating point number at the given index (min=-DBL_MAX, max=DBL_MAX, step=DBL_MIN)
      * `OBJECT` (json object): the child JSON object at the given index.
      * `ARRAY` (json array): the child JSON array at the given index.
      * `NULL` (empty): empty packet if the object is `null``
 * `json/array-length`:
    * Input Ports:
      * `IN` (json array, required): the input json to count elements
    * Output Ports:
      * `OUT` (irange): the number of child elements

Expected FBP to implement a webservice monitor:
```sh
rest_api_json OUT -> _(json/object-get-path:path="$.items[0].name") STRING -> console
rest_api_json OUT -> _(json/object-get-path:path="$.items[0].size") INT -> console
rest_api_json OUT -> _(json/object-get-key:key="enabled") BOOLEAN -> console
```

Sample FBP to print all keys of a given JSON object:
```sh
json_provider OUT -> IN json_get_key(json/object-get-key)

json_get_key STRING -> IN console
json_get_key BOOLEAN -> IN console
json_get_key INT -> IN console
json_get_key FLOAT -> IN console
json_get_key OBJECT -> IN console
json_get_key ARRAY -> IN console
json_get_key NULL -> IN console

# TODO: there is a race condition here if object-all-keys receives packet before object-get-key.
# The current implementation will work since object-all-keys packets will be processed after
# the packet is delivered to object-get-key, but new packets may arrive while not all keys were processed
json_provider OUT -> IN _(json/object-all-keys) OUT -> KEY json_get_key
```

## Creating JSON

To create JSON it's bit more tricky and needs more thinking. We should add key-value packet types for basic types, these will also be used to compose HTTP headers and eventually other items that need a label and a value.
 * `KEY_STRING`: used for string values
 * `KEY_BOOLEAN`: used for boolean values
 * `KEY_INT`: used for irange values
 * `KEY_FLOAT`: used for float values
 * `KEY_JSON_OBJECT`: used for JSON object values
 * `KEY_JSON_ARRAY`: used for JSON array values
 * ... likely other for all basic types such as timestamp, color and direction vector. These do not exist in JSON, but likely we'll need them for other purposes.

Some suggested node types:
 * `json/create-object`:
    * Input Ports:
      * `STRING` (key-string): the key with a string value.
      * `BOOLEAN` (key-boolean): the key with a boolean value
      * `INT` (key-irange): the key with an irange value
      * `FLOAT` (key-drange):  the key with a drange value
      * `OBJECT` (key-json-object): the key with a JSON object value
      * `ARRAY` (key-json-array): the key with a JSON array value
      * `NULL` (string): the key to create a value containing `null` (no payload is required, only the string/key)
      * `CREATE` (any): triggers the creation of the packet on `OUT` port.
      * `FLUSH` (any): triggers the flush of known key-value pairs (makes an empty object).
    * Output Ports:
      * `OUT` (json object): the object
 * `json/create-array`:
    * Input Ports:
      * `STRING` (string): the string to append/push as last element.
      * `BOOLEAN` (boolean): the boolean to append/push as last element.
      * `INT` (irange): the integer number to append/push as last element.
      * `FLOAT` (drange): the floating point number to append/push as last element.
      * `OBJECT` (json object): the child JSON object to append/push as last element.
      * `ARRAY` (json array): the child JSON array to append/push as last element.
      * `NULL` (empty): empty packet to append/push `null` as the last element.
      * `CREATE` (any): triggers the creation of the packet on `OUT` port.
      * `FLUSH` (any): triggers the flush of known children (makes an empty array).
    * Output Ports:
      * `OUT` (json array): the array
     * `COUNT` (irange): the number of elements in array (needed?)

FBP example:
```sh
json_creator(json/create-object)

# add "id": "soletta"
_(constant/key-value-string:key="id",value="soletta") OUT -> STRING json_creator

# add "uuid": "some-generated-uuid"
_(string/uuid) OUT -> IN _(key-value/string:key="uuid") OUT -> STRING json_creator

trigger OUT -> CREATE json_creator

json_creator OUT -> JSON rest_api

# usually rest_api will also have a trigger input port such as `SEND`, it should be activated by
# the json_creator OUT packet, not by the trigger OUT itself!
json_creator OUT -> SEND rest_api
```

**Comment by otaviobp** [comment]
done
