### ISSUE TITLE
Implementing HTTP generic nodes.

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#750]
I'm implementing for now: http/get-string, http/get-blob and http/request.

Leaving http/get-json as the last one, as we do not have the json nodes yet.

#748

**Comment by barbieri** [comment]
take a look at #756 and implement this node type inside that module.

**Comment by cabelitos** [comment]
Ok, I will close my pullreq and move them to @ceolin module.

**Comment by barbieri** [comment]
done in master
