### ISSUE TITLE
flow: file writer is sending packets from worker thread

### ISSUE THREAD

**Issue by barbieri** [solettaproject/soletta#890]
src/modules/flow/file/file.c uses a thread to write files and the error check is sending packets from the thread -- this is wrong as the flow is not supposed to be triggered from thread context.

change to use `sol_worker_thread_feedback()` and consuming the errors from the main thread callback.

**Comment by cabelitos** [comment]
I will take a look.

**Comment by cabelitos** [comment]
Please take a look at #910

**Comment by barbieri** [comment]
LGTM

**Comment by cabelitos** [comment]
Merged.
