### ISSUE TITLE
[P2] string-pcre-regexp-search.fbp failed to run on Galileo gen2 board

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#962]
version: v1-beta10 (sha1: 114cf120a7f4720c91e8ce1f5b3bdb7020694888)

- Output returned:
ERR:sol-flow-test ./src/modules/flow/test/result.c:74 fail() test/result node 'result_01' failed

- Complete output returned:
https://gist.github.com/anonymous/e0d25b1926a520ebb7f2

**Comment by anselmolsm** [comment]
Please, use a public pastebin service in public reports (e.g. https://gist.github.com, http://pastebin.com). This also applies to #963, #964 and #965. Tks.

**Comment by barbieri** [comment]
who compiled that libpcre? It's missing features, like the log says. It's not a soletta bug.

**Comment by dborquez** [comment]
The libpcre installed not satisfy the version >=8.12
- libpcre-dev - 8.35-r0.0
- libpcre1 - 8.35-r0.0
- libpcrecpp0 - 8.35-r0.0
- libpcreposix0 - 8.35-r0.0

**Comment by bdilly** [comment]
It was an issue with libpcre missing proper utf8 support.

It requires --enable-utf8 and --enable-unicode-properties

Fixed by https://github.com/solettaproject/meta-soletta/pull/33
