### ISSUE TITLE
[P2] persistence-fs-1 failed to run on Galileo Gen2

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#963]
version v1-beta10 (sha1:  114cf120a7f4720c91e8ce1f5b3bdb7020694888 )

- output returned:
ERR:sol-flow-test ./src/modules/flow/test/result.c:74 fail() test/result node '#anon:143:94' failed

- complete output returned:
https://gist.github.com/anonymous/224db592dea57ab7a4fa

**Comment by barbieri** [comment]
the log is related to another bug (javascript), please provide the paste for persistence failure.

Also, if you want you can open a Markdown block in your issue description. Use triple braces: `{{{` to start and `}}}` to end (each on its own lines)

**Comment by edersondisouza** [comment]
Soletta Galileo image [v1_beta11](https://github.com/solettaproject/meta-soletta/releases/tag/v6) and later should have this issue fixed. It is related to compilation flags.
