### ISSUE TITLE
[P2] string-pcre-regexp-replace.fbp failed to run on Galileo Gen2

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#964]
version v1-beta10 (sha1: 114cf120a7f4720c91e8ce1f5b3bdb7020694888)

- output returned: ERR:sol-flow-test ./src/modules/flow/test/result.c:74 fail() test/result node 'result_04' failed

- complete output: 
https://gist.github.com/anonymous/246bdb58d8042c9e3a56

**Comment by ceolin** [comment]
cant't reproduce
