### ISSUE TITLE
[P2] javascript.fbp test failed on Galileo Gen2

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#965]
version: v1-beta10 (sha1 114cf120a7f4720c91e8ce1f5b3bdb7020694888 )

- Output returned:
ERR:sol-flow ./src/lib/flow/sol-flow-parser.c:706 parse_declarations() Couldn't handle declaration 'MyScript' of metatype 'js'

- Complete output: 
https://gist.github.com/anonymous/833c3df837f4e8d40304

**Comment by barbieri** [comment]
who compiled soletta? did you use git submodules to download `duktape`? It is missing and thus was not compiled (`js.so`)

**Comment by dborquez** [comment]
I was not aware of that, because I based the build in the documentation available for the galileo:
https://github.com/solettaproject/soletta/wiki/Galileo-and-Galileo-Gen2-Instructions

After duktape and other submodules were installed the issue reported here has disappeared.

Thank you.

**Comment by barbieri** [comment]
@mbelluzzo or @anselmolsm, could you update the build instructions to reflect submodules usage?

**Comment by anselmolsm** [comment]
Added to https://github.com/solettaproject/soletta/wiki/Galileo-and-Galileo-Gen2-Instructions and  https://github.com/solettaproject/soletta/wiki/Build-requirements.
