### ISSUE TITLE
Document conffile search paths and order

### ISSUE THREAD

**Issue by mbelluzzo** [solettaproject/soletta#968]

**Comment by glima** [comment]
Why, if you have messed with that more recently?

**Comment by bdilly** [comment]
@mbelluzzo it would be nice to document it and also review our samples / demos fixing these names. If people continue to send PRs not using the expected naming I wouldn't discard the possibility of sending an email about it.

**Comment by barbieri** [comment]
also missing is the board detect to look for multiple files (ie: sorted by name, so we have 50-default.json, 01-my_override.json...)

otherwise people will ship packages with different pinmux but won't be used unless they add the new board to their board_detect.json)

**Comment by mbelluzzo** [comment]
#1055 + Added doc in the wiki
